.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "ZTEE" "1" "September 2017" "ZMap" "ztee"
.
.SH "NAME"
\fBztee\fR \- output buffer and splitter
.
.SH "SYNOPSIS"
ztee [ OPTIONS\.\.\. ] [ FILE\.\.\. ]
.
.SH "DESCRIPTION"
\fIZTee\fR is an output buffer and splitter for use with ZMap output data\. ZTee should be used whenever ZMap is piped into an application scanner, placed between ZMap and the application scanner\. ZTee writes the transformed output to stdout, and writes the original output to FILE\.
.
.P
See \fB\-\-help\fR for examples\.
.
.SH "CSV PROCESSING AND RAW MODE"
\fIZTee\fR operates by default on CSV\-format output from ZMap\. It only outputs IP addresses (from the input\'s \fBip\fR or \fBsaddr\fR field) to stdout, while writing all input to the output file\. ZTee does not print the first line of input to stdout, since that row is the CSV header\.
.
.P
To operate on data in any other format, pass the \fB\-\-raw\fR flag\. In raw mode, ztee behaves like tee: it will not transform or attempt to parse the input data\.
.
.SH "OPTIONS"
.
.SS "BASIC OPTIONS"
.
.TP
\fB\-r\fR, \fB\-\-raw\fR
Ignore input formatting and pass through raw input\. This causes ztee to behave exactly like tee, with the addition of buffering\.
.
.TP
\fB\-\-success\-only\fR
Only write to stdout rows where success=1 or success=true\. Invalid in combination with \fB\-\-raw\fR\.
.
.TP
\fB\-m\fR, \fB\-\-monitor\fR
Print monitor data to stderr
.
.TP
\fB\-u\fR, \fB\-\-status\-updates\-file\fR
Write status updates (monitor data) to the given file, in CSV format
.
.TP
\fB\-l\fR, \fB\-\-log\-file=name\fR
Write errors etc\. to the given file\. If none, ZTee logs to stderr\.
.
.SS "ADDITIONAL OPTIONS"
.
.TP
\fB\-h, \-\-help\fR
Display help
.
.TP
\fB\-V, \-\-version\fR
Display version

