name: CMake-Linux-and-BSD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  ENABLE_DEVELOPMENT: ON
  ENABLE_LOG_TRACE: ON

jobs:
  build-ubuntu:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/zmap/builder:2023-09-10
      volumes:
        - ${{github.workspace}}:/zmap
    steps:
      - uses: actions/checkout@v2

      - name: Make build directory
        run: mkdir -p /zmap/build

      - name: Configure CMake
        working-directory: /zmap/build
        # Configure CMake in a 'build' subdirectory.
        run: cmake -DENABLE_DEVELOPMENT=${{env.ENABLE_DEVELOPMENT}} -DENABLE_LOG_TRACE=${{env.ENABLE_LOG_TRACE}} /zmap

      - name: Build
        working-directory: /zmap/build
        # Build your program with the given configuration
        run: make

      - name: Check Manpages
        working-directory: /zmap
        run: python3 ./scripts/check_manfile.py

  build-debian:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: looking around
        run: ls -a .github/workflows/
      - name: Check Debian Compilation
        run: |
          docker build -t debian-container -f .github/workflows/debian.Dockerfile .
          docker run debian-container

