name: CMake-Debian

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  ENABLE_DEVELOPMENT: ON
  ENABLE_LOG_TRACE: ON

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          cat <<EOF | docker buildx build --platform linux/amd64 --tag myapp:debian -
          FROM debian:bullseye 
          RUN apt-get update
          RUN apt-get install -y build-essential cmake libgmp3-dev gengetopt libpcap-dev flex byacc libjson-c-dev \
            pkg-config libunistring-dev libjudy-dev cmake  make python3
          RUN apt-get clean
          RUN rm -rf /var/lib/apt/lists/*

          WORKDIR /zmap

          COPY . .

          RUN ls
          RUN cmake -DENABLE_DEVELOPMENT=$ENABLE_DEVELOPMENT -DENABLE_LOG_TRACE=$ENABLE_LOG_TRACE .
          RUN make
          RUN cd ..
          RUN python3 ./scripts/check_manfile.py


               EOF

      - name: Run Docker container
        run: docker run --rm -v ${{ github.workspace }}:/zmap myapp:debian
