name: CMake-MacOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  ENABLE_DEVELOPMENT: ON
  ENABLE_LOG_TRACE: ON

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v2

      - name: Download dependencies
        run: brew install pkg-config cmake gmp gengetopt json-c byacc libunistring judy

        # TODO Phillip remove this, just for testing
      - name: Look around
        run: ls

      - name: Configure CMake
        # Configure CMake in a 'build' subdirectory.
        run: cmake -DENABLE_DEVELOPMENT=${{env.ENABLE_DEVELOPMENT}} -DENABLE_LOG_TRACE=${{env.ENABLE_LOG_TRACE}} .

      - name: Build
        # Build your program with the given configuration
        run: make

      - name: Check Manpages
        run: python3 ./scripts/check_manfile.py
